// Editor document ⇄ Rust document mapping, and the element-level diff the
// editor sends to Rust (`screenplay.apply_edits`). Pure functions, unit-tested.
//
// Rust is the source of truth: the editor keeps a *baseline* snapshot of what
// Rust has, and sends the ops that turn the baseline into the current editor
// state. Ops are generated by simulating their effect so every index refers
// to the state after the previous op — the same semantics Rust applies.

import type { Node as PMNode, Slice } from "prosemirror-model";
import type { Transaction } from "prosemirror-state";
import type { ElementType } from "../../../ipc/generated/ElementType";
import type { ScreenplayEditOp } from "../../../ipc/generated/ScreenplayEditOp";
import type { ScreenplaySceneDto } from "../../../ipc/generated/ScreenplaySceneDto";
import { ELEMENT_META, isElementType, schema } from "./schema";

export interface ElementSnap {
  id: string;
  type: ElementType;
  text: string;
}

export interface SceneSnap {
  id: string;
  heading: string;
  elements: ElementSnap[];
}

export type Snapshot = SceneSnap[];

export function snapshotFromScenes(scenes: ScreenplaySceneDto[]): Snapshot {
  return scenes.map((s) => ({
    id: s.id,
    heading: s.heading,
    elements: s.elements.map((e) => ({ id: e.id, type: e.elementType, text: e.text })),
  }));
}

function inlineContent(type: ElementType, text: string): PMNode[] {
  const multiline = ELEMENT_META[type].multiline;
  const lines = multiline ? text.split("\n") : [text.replace(/\n/g, " ")];
  const out: PMNode[] = [];
  lines.forEach((line, i) => {
    if (i > 0) out.push(schema.nodes.hard_break.create());
    if (line.length > 0) out.push(schema.text(line));
  });
  return out;
}

export function docFromSnapshot(snap: Snapshot): PMNode {
  const blocks: PMNode[] = [];
  for (const scene of snap) {
    blocks.push(schema.nodes.scene_heading.create({ id: scene.id }, inlineContent("scene_heading", scene.heading)));
    for (const el of scene.elements) {
      const type = el.type === "scene_heading" ? "action" : el.type;
      blocks.push(schema.nodes[type].create({ id: el.id }, inlineContent(type, el.text)));
    }
  }
  if (blocks.length === 0) blocks.push(schema.nodes.scene_heading.create({ id: null }));
  return schema.nodes.doc.create(null, blocks);
}

export function blockText(node: PMNode): string {
  return node.textBetween(0, node.content.size, undefined, "\n");
}

/** Read the editor document as scenes. Blocks without ids are skipped (ids are
 * assigned by the editor's id plugin before any sync happens). */
export function snapshotFromDoc(doc: PMNode): Snapshot {
  const out: Snapshot = [];
  doc.forEach((node) => {
    const type = node.type.name;
    const id = node.attrs.id as string | null;
    if (!id || !isElementType(type)) return;
    if (type === "scene_heading") {
      out.push({ id, heading: blockText(node), elements: [] });
    } else if (out.length > 0) {
      out[out.length - 1].elements.push({ id, type, text: blockText(node) });
    }
  });
  return out;
}

export function snapshotsEqual(a: Snapshot, b: Snapshot): boolean {
  if (a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) {
    const x = a[i];
    const y = b[i];
    if (x.id !== y.id || x.heading !== y.heading || x.elements.length !== y.elements.length) return false;
    for (let j = 0; j < x.elements.length; j++) {
      const e = x.elements[j];
      const f = y.elements[j];
      if (e.id !== f.id || e.type !== f.type || e.text !== f.text) return false;
    }
  }
  return true;
}

interface SimScene {
  id: string;
  els: string[];
}

/** Ops that transform `base` into `next` (see module comment). */
export function diffSnapshots(base: Snapshot, next: Snapshot): ScreenplayEditOp[] {
  const ops: ScreenplayEditOp[] = [];
  const baseEl = new Map<string, ElementSnap>();
  const baseHeading = new Map<string, string>();
  const loc = new Map<string, string>();
  const sim: SimScene[] = base.map((s) => {
    baseHeading.set(s.id, s.heading);
    for (const e of s.elements) {
      baseEl.set(e.id, e);
      loc.set(e.id, s.id);
    }
    return { id: s.id, els: s.elements.map((e) => e.id) };
  });
  const nextScenes = new Set(next.map((s) => s.id));
  const nextEls = new Set<string>();
  for (const s of next) for (const e of s.elements) nextEls.add(e.id);

  // 1. Elements that vanished from surviving scenes are deleted. Elements of a
  //    scene that disappears entirely stay with it (recoverable scene delete).
  for (const s of sim) {
    if (!nextScenes.has(s.id)) continue;
    s.els = s.els.filter((id) => {
      if (nextEls.has(id)) return true;
      ops.push({ op: "deleteElement", id });
      loc.delete(id);
      return false;
    });
  }

  // 2. Scenes: insert new ones and move existing ones into order.
  next.forEach((ns, i) => {
    const at = sim.findIndex((s) => s.id === ns.id);
    if (at === -1) {
      ops.push({ op: "insertScene", id: ns.id, index: i, heading: ns.heading });
      sim.splice(Math.min(i, sim.length), 0, { id: ns.id, els: [] });
    } else if (at !== i) {
      ops.push({ op: "moveScene", id: ns.id, index: i });
      const [moved] = sim.splice(at, 1);
      sim.splice(Math.min(i, sim.length), 0, moved);
    }
  });

  // 3. Elements: insert, move, update.
  const simById = new Map(sim.map((s) => [s.id, s] as const));
  for (const ns of next) {
    const target = simById.get(ns.id)!;
    ns.elements.forEach((ne, j) => {
      const from = loc.get(ne.id);
      if (from === undefined) {
        ops.push({ op: "insertElement", id: ne.id, sceneId: ns.id, index: j, elementType: ne.type, text: ne.text });
        target.els.splice(Math.min(j, target.els.length), 0, ne.id);
        loc.set(ne.id, ns.id);
        return;
      }
      const src = simById.get(from)!;
      const cur = src.els.indexOf(ne.id);
      if (from !== ns.id || cur !== j) {
        ops.push({ op: "moveElement", id: ne.id, sceneId: ns.id, index: j });
        src.els.splice(cur, 1);
        target.els.splice(Math.min(j, target.els.length), 0, ne.id);
        loc.set(ne.id, ns.id);
      }
      const b = baseEl.get(ne.id)!;
      if (b.type !== ne.type || b.text !== ne.text) {
        const op: ScreenplayEditOp = { op: "updateElement", id: ne.id };
        if (b.type !== ne.type) op.elementType = ne.type;
        if (b.text !== ne.text) op.text = ne.text;
        ops.push(op);
      }
    });
  }

  // 4. Scenes that disappeared (recoverable delete, keeping leftover elements).
  for (const s of sim) {
    if (!nextScenes.has(s.id)) ops.push({ op: "deleteScene", id: s.id });
  }

  // 5. Heading text.
  for (const ns of next) {
    const old = baseHeading.get(ns.id);
    if (old !== undefined && old !== ns.heading) ops.push({ op: "updateScene", id: ns.id, heading: ns.heading });
  }
  return ops;
}

/** Apply ops to a snapshot with Rust's semantics (used to verify the diff in tests). */
export function applyOps(base: Snapshot, ops: ScreenplayEditOp[]): Snapshot {
  const scenes = base.map((s) => ({ ...s, elements: s.elements.map((e) => ({ ...e })) }));
  const deleted = new Set<string>();
  const live = () => scenes.filter((s) => !deleted.has(s.id));
  const findEl = (id: string) => {
    for (const s of scenes) {
      const i = s.elements.findIndex((e) => e.id === id);
      if (i >= 0) return { s, i };
    }
    throw new Error(`element ${id} not found`);
  };
  const place = <T,>(arr: T[], item: T, index: number | undefined) => {
    arr.splice(index === undefined ? arr.length : Math.min(index, arr.length), 0, item);
  };
  for (const op of ops) {
    switch (op.op) {
      case "insertElement": {
        const s = scenes.find((x) => x.id === op.sceneId)!;
        place(s.elements, { id: op.id!, type: op.elementType, text: op.text }, op.index);
        break;
      }
      case "updateElement": {
        const { s, i } = findEl(op.id);
        if (op.elementType) s.elements[i].type = op.elementType;
        if (op.text !== undefined) s.elements[i].text = op.text;
        break;
      }
      case "deleteElement": {
        const { s, i } = findEl(op.id);
        s.elements.splice(i, 1);
        break;
      }
      case "moveElement": {
        const { s, i } = findEl(op.id);
        const [el] = s.elements.splice(i, 1);
        place(scenes.find((x) => x.id === op.sceneId)!.elements, el, op.index);
        break;
      }
      case "insertScene": {
        const l = live();
        const at = op.index === undefined || op.index >= l.length ? scenes.length : scenes.indexOf(l[op.index]);
        scenes.splice(at, 0, { id: op.id!, heading: op.heading, elements: [] });
        break;
      }
      case "moveScene": {
        const s = scenes.find((x) => x.id === op.id)!;
        scenes.splice(scenes.indexOf(s), 1);
        const l = live();
        const at = op.index >= l.length ? scenes.length : scenes.indexOf(l[op.index]);
        scenes.splice(at, 0, s);
        break;
      }
      case "updateScene":
        scenes.find((x) => x.id === op.id)!.heading = op.heading;
        break;
      case "deleteScene":
        deleted.add(op.id);
        break;
      default:
        throw new Error(`unsupported op ${op.op}`);
    }
  }
  return live();
}

/**
 * Whether a transaction can have created blocks (split, paste, node changes).
 * Typing only inserts text, so per-keystroke work over all blocks can be skipped.
 */
export function mayAddBlocks(tr: Transaction): boolean {
  return tr.steps.some((step) => {
    const slice = (step as unknown as { slice?: Slice }).slice;
    if (!slice) return true;
    let block = false;
    slice.content.descendants((n) => {
      if (n.isBlock) block = true;
      return !block;
    });
    return block;
  });
}
